export const HomeItems = [
  {
    title: "FirstYear",
    url: "/first",
    image: "/Resources/Moon.svg",
    cHame: "route-link",
    text: "Get the first year resources of each subject material with its five previous year papers",
  },
  {
    title: "SecondYear",
    url: "/second",
    image: "/Resources/learn.svg",
    cHame: "route-link",
    text: "Get the Second year resources of each subject material with its five previous year papers",
  },
  {
    title: "ThirdYear",
    url: "https://drive.google.com/drive/folders/1EpKQKGtg6AVw2S7OTY_gztKcIXyohUXQ?usp=sharing",
    image: "/Resources/learn.svg",
    cHame: "route-link",
    text: "Get the Third year resources of each subject material with its five previous year papers",
  },
  {
    title: "FourthYear",
    url: "https://drive.google.com/drive/folders/1bPnRXCBXUywn9YqREpuXbx0yULZTvcbz?usp=sharing",
    image: "/Resources/learn.svg",
    cHame: "route-link",
    text: "Get the Fourth year resources of each subject material with its five previous year papers",
  },
  {
    title: "CSE-101",
    url: "/cse",
    image: "/Resources/exams.svg",
    cHame: "route-link",
    text: "Get the some important, unique, and useful computer science content ",
  },
  {
    title: "Self-Dev",
    url: "/self",
    image: "/Resources/exams.svg",
    cHame: "route-link",
    text: "Improve you personality with the resources like e-books,tools and many more",
  },
  {
    title: "Contribute",
    url: "/contribute",
    image: "/Resources/booklover.svg",
    cHame: "route-link",
    text: "Contribute to this website by providing content you think is necessary for this website",
  },
];
